version: "3.3"
services:

  consul:
    image: consul:1.5.2
    command: ["consul","agent","-config-file=/config/consul.hcl","-config-dir=/config"]
    volumes:
      - "./consul_config:/config"
    ports:
      - 8500:8500
    networks:
      vpcbr:
        ipv4_address: 10.5.0.2

  # Define downstream service and proxy
  downstream:
    image: golang:alpine
    command: [
      'go','run','/app/main.go','--bind-address=10.5.0.3:9000','--upstream-uri=http://127.0.0.1:9001']
    volumes:
      - "./service:/app"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.3
    ports:
      - 9000:9000
    environment:
      GO111MODULE: 'on'
  downstream_envoy:
    image: envoyproxy/envoy-alpine:v1.9.1
    command: ["envoy","-c","/config/downstream_envoy.json"]
    volumes:
      - "./envoy_config:/config"
    network_mode: "service:downstream"

  # Define upstream service and proxy
  upstream:
    image: golang:alpine
    command: [
      'go','run','/app/main.go','--bind-address=127.0.0.1:9001','--type=upstream', '--upstream-errors=0.1']
    volumes:
      - "./service:/app"
    networks:
      vpcbr:
        ipv4_address: 10.5.0.4
    environment:
      GO111MODULE: 'on'
  upstream_proxy:
    image: envoyproxy/envoy-alpine:v1.9.1
    command: ["envoy","-c","/config/upstream_envoy.json"]
    volumes:
      - "./envoy_config:/config"
    network_mode: "service:upstream"

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.5.0.0/16
